### PR TITLE
[for review] Add a blog to the Moby Project website

### PR DESCRIPTION
**Pull request by amirmc**
The styling of the site could use some work but the following adds a blog to the Moby site.  It's incomplete as it still needs:
- Navigation links (right now you manually go to `/blog`)
- An Atom/RSS feed (there's probably a `gem` that will do this).
- UI elements for both the above :)
- See also #4

Still, this should be enough to demonstrate the pieces.

cc @chanezon @vieux

### CODE REVIEW

**Comment by amirmc** [comment]
It also needs a decision on the kind of URL scheme before merge. See my comments in #4.

**Comment by amirmc** [comment]
There's more work to do in terms of of navigation and styling. Using something like [Zurb foundation](http://foundation.zurb.com) would make alignments etc easier. I'll leave all that to someone more experienced though cc/ @FSHA :)

@chanezon I think this is now ready to merge.

**Comment by amirmc** [comment]
@avsm When your script is working, you may want to undo the content of https://github.com/moby/mobywebsite/pull/5/commits/c65365d109a923e92a8727e95b195d502b9c023d

**Comment by chanezon** [comment]
Thank you @amirmc looks great!

**Pull request merged**
