### PR TITLE
Fix Markdown, links and more

### PR DESCRIPTION
**Pull request by xchopin**
- Fix GitHub links (blob/moby instead of blob/master)
- Refractor code (indentation)
- Update footer (year 2017 to year 2019)
- Fix images in some documents

### CODE REVIEW

**Comment by xchopin** [comment]
@chanezon Thank you to take a look to these updates :)

**Comment by chanezon** [comment]
@xchopin Thank you for the update, but I am not involved with the Moby project these days. 
On the copyright date update, I'm not sure you're supposed to update the date.
@crosbymichael who would be a good maintainer for the Moby website?

**Comment by xchopin** [comment]
Thanks for your reply,

My bad for the tag, I just saw you were the last contributor of this project, that's why 😅
I didn't know about the copyright thing, I can remove my commit if it's required

PS: je viens de remarquer que vous êtes français ! :) 🥖

**Comment by tnir** [comment]
It looks we are gathering similar PRs #40 #41 #44 #46 as well as moby/moby#40350 as an issue on moby/moby.

Does anyone merge this?

cc @crosbymichael

**Comment by AkihiroSuda** [comment]
@thaJeztah PTAL?

**Comment by tnir** [comment]
@justincormack Thanks for merging. How can you deploy them to https://mobyproject.org/ ? The website is not changed yet.


cc @AkihiroSuda

**Comment by MACEL94** [comment]
This is still not fixed, i'm new to the project but immediately noticed... not a great start to get a broken link in the homepage...

I'd be glad to contribute but this seems fixed and merged... can i ask why not deployed then?

**Pull request merged**
